-- CreateEnum
CREATE TYPE "WeeklyPlanStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "PlannerGoalCategory" AS ENUM ('IMMERSION', 'KANJI', 'VOCABULARY', 'GRAMMAR', 'GENERAL_REVIEW', 'READING', 'ACTIVE_STUDY', 'PASSIVE_STUDY');

-- CreateEnum
CREATE TYPE "PlannerCategory" AS ENUM ('KANJI', 'VOCABULARY', 'GRAMMAR', 'CHUNK', 'READING', 'IMMERSION', 'ACTIVE_STUDY', 'PASSIVE_STUDY', 'REVIEW', 'GENERAL', 'OTHER');

-- CreateEnum
CREATE TYPE "PlannerTaskPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- CreateEnum
CREATE TYPE "PlannerTaskStatus" AS ENUM ('PENDING', 'COMPLETED');

-- CreateTable
CREATE TABLE "weekly_plans" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "weekNumber" INTEGER NOT NULL,
    "startDate" VARCHAR(10) NOT NULL,
    "endDate" VARCHAR(10) NOT NULL,
    "status" "WeeklyPlanStatus" NOT NULL DEFAULT 'ACTIVE',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "weekly_plans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "weekly_goals" (
    "id" TEXT NOT NULL,
    "weeklyPlanId" TEXT NOT NULL,
    "category" "PlannerGoalCategory" NOT NULL,
    "targetValue" INTEGER NOT NULL,
    "unit" VARCHAR(20) NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "weekly_goals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "planner_tasks" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "weeklyPlanId" TEXT,
    "title" VARCHAR(300) NOT NULL,
    "description" TEXT,
    "category" "PlannerCategory" NOT NULL DEFAULT 'GENERAL',
    "date" VARCHAR(10) NOT NULL,
    "scheduledTime" VARCHAR(10),
    "estimatedMinutes" INTEGER NOT NULL DEFAULT 15,
    "actualMinutes" INTEGER,
    "priority" "PlannerTaskPriority" NOT NULL DEFAULT 'MEDIUM',
    "status" "PlannerTaskStatus" NOT NULL DEFAULT 'PENDING',
    "completedAt" TIMESTAMP(3),
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "actionPayload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "planner_tasks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "weekly_plans_userId_startDate_idx" ON "weekly_plans"("userId", "startDate");

-- CreateIndex
CREATE UNIQUE INDEX "weekly_plans_userId_year_weekNumber_key" ON "weekly_plans"("userId", "year", "weekNumber");

-- CreateIndex
CREATE INDEX "weekly_goals_weeklyPlanId_idx" ON "weekly_goals"("weeklyPlanId");

-- CreateIndex
CREATE UNIQUE INDEX "weekly_goals_weeklyPlanId_category_key" ON "weekly_goals"("weeklyPlanId", "category");

-- CreateIndex
CREATE INDEX "planner_tasks_userId_date_idx" ON "planner_tasks"("userId", "date");

-- CreateIndex
CREATE INDEX "planner_tasks_userId_status_idx" ON "planner_tasks"("userId", "status");

-- CreateIndex
CREATE INDEX "planner_tasks_weeklyPlanId_idx" ON "planner_tasks"("weeklyPlanId");

-- AddForeignKey
ALTER TABLE "weekly_plans" ADD CONSTRAINT "weekly_plans_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "weekly_goals" ADD CONSTRAINT "weekly_goals_weeklyPlanId_fkey" FOREIGN KEY ("weeklyPlanId") REFERENCES "weekly_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "planner_tasks" ADD CONSTRAINT "planner_tasks_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "planner_tasks" ADD CONSTRAINT "planner_tasks_weeklyPlanId_fkey" FOREIGN KEY ("weeklyPlanId") REFERENCES "weekly_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;
